---
- name: Ensure __role_name is defined
  ansible.builtin.assert:
    that:
      - __role_name is defined
      - __role_name is string
      - __role_name | length > 0
      # Make sure I don't forget to replace the role name
      # This assert failing also ensures this role is not uploaded to Ansible Galaxy
      - "__role_name != ['temp', 'late'] | join('')"

- name: Ensure variables are changed
  ansible.builtin.assert:
    that:
      - jetbrains_common_name != "xxxxx"
      - jetbrains_common_stylized_name != "xxxxx"
      - jetbrains_common_version != "xxxxx.x"
      - jetbrains_common_edition != "xxxxx"

...
