---
- name: Include common role
  ansible.builtin.include_role:
    name: diademiemi.jetbrains.common
    tasks_from: main.yml
  vars:
    jetbrains_common_name: "{{ jetbrains_pycharm_name }}"
    jetbrains_common_stylized_name: "{{ jetbrains_pycharm_stylized_name }}"
    jetbrains_common_version: "{{ jetbrains_pycharm_version }}"
    jetbrains_common_edition: "{{ jetbrains_pycharm_edition }}"
    jetbrains_common_naming_map: "{{ jetbrains_pycharm_naming_map }}"
    jetbrains_common_url: "{{ jetbrains_pycharm_url }}"
    jetbrains_common_url_prefix: "{{ jetbrains_pycharm_url_prefix }}"
    jetbrains_common_plugins: "{{ jetbrains_pycharm_plugins }}"
    jetbrains_common_plugins_user: "{{ jetbrains_pycharm_plugins_user }}"
    jetbrains_common_plugins_group: "{{ jetbrains_pycharm_plugins_group }}"

...
