---
- name: Include common role
  ansible.builtin.include_role:
    name: diademiemi.jetbrains.common
    tasks_from: main.yml
  vars:
    jetbrains_common_name: "{{ jetbrains_phpstorm_name }}"
    jetbrains_common_stylized_name: "{{ jetbrains_phpstorm_stylized_name }}"
    jetbrains_common_version: "{{ jetbrains_phpstorm_version }}"
    jetbrains_common_edition: "{{ jetbrains_phpstorm_edition }}"
    jetbrains_common_naming_map: "{{ jetbrains_phpstorm_naming_map }}"
    jetbrains_common_url: "{{ jetbrains_phpstorm_url }}"
    jetbrains_common_url_prefix: "{{ jetbrains_phpstorm_url_prefix }}"
    jetbrains_common_plugins: "{{ jetbrains_phpstorm_plugins }}"
    jetbrains_common_plugins_user: "{{ jetbrains_phpstorm_plugins_user }}"
    jetbrains_common_plugins_group: "{{ jetbrains_phpstorm_plugins_group }}"

...
